First version of the IRCv2 implementation
JoDehli/PyLoxone pull request #35
Opened 2020-09-25 11:28 UTC by ztamas83

I have started the implementation of the IntelligentRoomController v2 against the Home-Assistant climate entity.
With this version the changes are synced both ways between HA and Loxone.

This is my very first work in HA so all comments and corrections are welcome.

2020-09-25 18:02 UTC, JoDehli commented on custom_components/loxone/climate.py
> +    PRESET_AWAY,
These const are not needed:
   
 PRESET_COMFORT,
    PRESET_ECO,
    PRESET_AWAY,

2020-09-25 18:02 UTC, JoDehli commented on custom_components/loxone/climate.py
> +from typing import Any
These imports are not needed:
import collections
from typing import Any

2020-09-25 18:03 UTC, JoDehli commented on custom_components/loxone/climate.py
> +from homeassistant.helpers.event import track_utc_time_change
track_utc_time_change import is not needed

2020-09-25 18:04 UTC, JoDehli commented on custom_components/loxone/climate.py
> +    autoMode = 0 if config.get(CONF_HVAC_AUTO_MODE) is None else config.get(CONF_HVAC_AUTO_MODE)
autoMode variable should be lowercase for example: auto_mode

2020-09-25 18:06 UTC, JoDehli commented on custom_components/loxone/climate.py
> +        targetMode = self.autoMode if hvac_mode == HVAC_MODE_AUTO else OPMODETOLOXONE[hvac_mode]
targetMode should be lowercase for example target_mode

2020-09-25 18:09 UTC, JoDehli requested changes
Only a view format and variables names should be changed. Again great work. Thanks.

What I must do is also use the new f-string notation. Looks much better :-)

2020-09-25 18:10 UTC, JoDehli commented on custom_components/loxone/climate.py
> +from typing import Any
of course logging must stay!

2020-09-25 19:50 UTC, ztamas83 commented
Two config things I don't really know how to solve:
1) Different controllers in different rooms may have different capabilities (HVAC modes), users perhaps should be able to set the capabilities in config instead of automatically add all units with all capabilities? E.g. I only have heater control, should not be able to set HVAC_COOL
2) Same for the auto mode, if i want Auto heat/cool, or just auto heat or auto cool. For this I already added the config but I'm not sure how to add the config into HASS. Need to figure it out.

Maybe they are for the next release if the basic IRCv2 functionality is so awaited :)

I'll push the changes you commented on.

2020-09-26 06:19 UTC, merged

2020-09-26 07:01 UTC, JoDehli commented
Thanks again for your work. I am glad that somebody helps me. Because I have not so much time and a view other projects I am working on. I merged it and made some smaller changes. It is only because my IDE complaints about some PEP errors. For example some variables names. And I changed the name of the RoomController to RoomControllerV2. 

I must think about your questions. For now I have no solutions. But I think we have time to improve it. I wanted to release it because some users are already requested the RoomController. But I think the best would be to get the information automatically from the loxone. I do not know it but does the official Loxone app recognize if a entity only have a heating or not? The same information should also be available for us.

2020-09-27 00:47 UTC, MaartenMees commented
Thanks Guys!!!